### PR TITLE
Fix font names

### PR DESCRIPTION
**Pull request by m4rc1e**
This PR fixes the font names so it will work on Mac, Linux and Win. Please note, several fontbakery checks currently fail. These are false positives and I'll eventually fix fontbakery so it passes.

Fontbakery currently assumes a font will always have a Regular style. All of our families from inception till 2023 had a weight axis so it was a baked in requirement. In 2023, Kablammo was released. This family has a MORF axis and no true Regular style. The current name table setup of this family isn't quite right. The nametable's familyname is Regular, yet the default instance is Zoink. In Agu, the familyname is Uzo and the default instance is also Uzo, which is what we want. 

In Windows, the variable font is working correctly in Ms Word.

Here's a dump of the name table, fvar and STAT.

```XML
<?xml version="1.0" encoding="UTF-8"?>
<ttFont sfntVersion="\x00\x01\x00\x00" ttLibVersion="4.54">

  <name>
    <namerecord nameID="256" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Morph
    </namerecord>
    <namerecord nameID="257" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Uzo
    </namerecord>
    <namerecord nameID="258" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Ala
    </namerecord>
    <namerecord nameID="259" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Osisi
    </namerecord>
    <namerecord nameID="0" platformID="3" platEncID="1" langID="0x409">
      Copyright 2024 The Agu Display Project Authors (https://github.com/theseunbadejo/nsibidi-libre/blob/main/AUTHORS.txt)
    </namerecord>
    <namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
      Agu Display Uzo
    </namerecord>
    <namerecord nameID="2" platformID="3" platEncID="1" langID="0x409">
      Regular
    </namerecord>
    <namerecord nameID="3" platformID="3" platEncID="1" langID="0x409">
      1.096;53VN;AguDisplay-Uzo
    </namerecord>
    <namerecord nameID="4" platformID="3" platEncID="1" langID="0x409">
      Agu Display Uzo
    </namerecord>
    <namerecord nameID="5" platformID="3" platEncID="1" langID="0x409">
      Version 1.096
    </namerecord>
    <namerecord nameID="6" platformID="3" platEncID="1" langID="0x409">
      AguDisplay-Uzo
    </namerecord>
    <namerecord nameID="9" platformID="3" platEncID="1" langID="0x409">
      Oluwaseun Badejo
    </namerecord>
    <namerecord nameID="12" platformID="3" platEncID="1" langID="0x409">
      https://seun.design
    </namerecord>
    <namerecord nameID="13" platformID="3" platEncID="1" langID="0x409">
      This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: https://openfontlicense.org
    </namerecord>
    <namerecord nameID="14" platformID="3" platEncID="1" langID="0x409">
      https://openfontlicense.org
    </namerecord>
    <namerecord nameID="16" platformID="3" platEncID="1" langID="0x409">
      Agu Display
    </namerecord>
    <namerecord nameID="17" platformID="3" platEncID="1" langID="0x409">
      Uzo
    </namerecord>
    <namerecord nameID="25" platformID="3" platEncID="1" langID="0x409">
      AguDisplay
    </namerecord>
    <namerecord nameID="256" platformID="3" platEncID="1" langID="0x409">
      Morph
    </namerecord>
    <namerecord nameID="257" platformID="3" platEncID="1" langID="0x409">
      Uzo
    </namerecord>
    <namerecord nameID="258" platformID="3" platEncID="1" langID="0x409">
      Ala
    </namerecord>
    <namerecord nameID="259" platformID="3" platEncID="1" langID="0x409">
      Osisi
    </namerecord>
  </name>

  <fvar>

    <!-- Morph -->
    <Axis>
      <AxisTag>MORF</AxisTag>
      <Flags>0x0</Flags>
      <MinValue>0.0</MinValue>
      <DefaultValue>0.0</DefaultValue>
      <MaxValue>60.0</MaxValue>
      <AxisNameID>256</AxisNameID>
    </Axis>

    <!-- Uzo -->
    <NamedInstance flags="0x0" subfamilyNameID="257">
      <coord axis="MORF" value="0.0"/>
    </NamedInstance>

    <!-- Ala -->
    <NamedInstance flags="0x0" subfamilyNameID="258">
      <coord axis="MORF" value="30.0"/>
    </NamedInstance>

    <!-- Osisi -->
    <NamedInstance flags="0x0" subfamilyNameID="259">
      <coord axis="MORF" value="60.0"/>
    </NamedInstance>
  </fvar>

  <STAT>
    <Version value="0x00010001"/>
    <DesignAxisRecordSize value="8"/>
    <!-- DesignAxisCount=1 -->
    <DesignAxisRecord>
      <Axis index="0">
        <AxisTag value="MORF"/>
        <AxisNameID value="256"/>  <!-- Morph -->
        <AxisOrdering value="0"/>
      </Axis>
    </DesignAxisRecord>
    <!-- AxisValueCount=3 -->
    <AxisValueArray>
      <AxisValue index="0" Format="1">
        <AxisIndex value="0"/>
        <Flags value="0"/>
        <ValueNameID value="257"/>  <!-- Uzo -->
        <Value value="0.0"/>
      </AxisValue>
      <AxisValue index="1" Format="1">
        <AxisIndex value="0"/>
        <Flags value="0"/>
        <ValueNameID value="258"/>  <!-- Ala -->
        <Value value="30.0"/>
      </AxisValue>
      <AxisValue index="2" Format="1">
        <AxisIndex value="0"/>
        <Flags value="0"/>
        <ValueNameID value="259"/>  <!-- Osisi -->
        <Value value="60.0"/>
      </AxisValue>
    </AxisValueArray>
    <ElidedFallbackNameID value="2"/>  <!-- Regular -->
  </STAT>

</ttFont>
```

In order for this pr to work, I've had to update gftools so you'll see the requirements have changed.

### CODE REVIEW

**Comment by m4rc1e** [comment]
cc @n8willis

**Review by n8willis — APPROVED** [review]
Looks good of course. I am curious about the .glyphs filename change, though — does that affect something, or is it just on principle?

**Comment by m4rc1e** [comment]
the exported variable font is named `Agu_Display` when the source filename includes the underscore.

**Review by theseunbadejo — APPROVED** [review]

**Comment by theseunbadejo** [comment]
This looks great @m4rc1e thanks a lot for the help and for catching the "underscore" as well. I just merged the commit.

**Pull request merged**
